openapi: "3.0.0"
info:
  title: Applications API
  version: 1.0.0

paths:
  /api/v0/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationCollection"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    post:
      tags:
        - application
      summary: Create an application
      operationId: createApplication
      requestBody:
        description: create an application
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationCreateRequest'
      responses:
        '201':
          description: 'Created'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

  /api/v0/applications/{id}:
    get:
      summary: Get application by id
      operationId: getApplicationById
      tags:
        - application
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the application to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    patch:
      tags:
        - application
      summary: Update an application
      operationId: updateApplication
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the application to update
          schema:
            type: string
            format: uuid
      requestBody:
        description: update an existing item
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationUpdateRequest'
      responses:
        '204':
          description: No content
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
    delete:
      summary: Delete application by id
      operationId: deleteApplication
      tags:
        - application
      parameters:
        - name: id
          in: path
          required: true
          description: The id of the application to be deleted
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: No content
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '403':
          description: 'Forbidden'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'

components:
  schemas:
    Application:
      required:
        - id
        - provider_firm_id
        - provider_office_id
        - client_id
      properties:
        id:
          type: string
          format: uuid
        provider_firm_id:
          type: string
        provider_office_id:
          type: string
        client_id:
          type: string
          format: uuid
        status_code:
          type: string
        statement_of_case:
          type: string
        is_emergency_application:
          type: boolean
        proceedings:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationProceeding"
      allOf:
        - $ref: "#/components/schemas/RecordHistory"

    ApplicationCreateRequest:
      required:
        - provider_firm_id
        - provider_office_id
        - client_id
      properties:
        provider_firm_id:
          type: string
        provider_office_id:
          type: string
        client_id:
          type: string
          format: uuid
        status_code:
          type: string
        statement_of_case:
          type: string
        is_emergency_application:
          type: boolean
        proceedings:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationProceedingCreateRequest"

    ApplicationUpdateRequest:
      properties:
        provider_firm_id:
          type: string
        provider_office_id:
          type: string
        client_id:
          type: string
          format: uuid
        status_code:
          type: string
        statement_of_case:
          type: string
        is_emergency_application:
          type: boolean
        proceedings:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationProceedingUpdateRequest"

    ApplicationProceeding:
      properties:
        id:
          type: string
          format: uuid
        proceeding_code:
          type: string
        level_of_service_code:
          type: string
      allOf:
        - $ref: "#/components/schemas/RecordHistory"

    ApplicationProceedingCreateRequest:
      required:
        - proceeding_code
      properties:
        proceeding_code:
          type: string
        level_of_service_code:
          type: string

    ApplicationProceedingUpdateRequest:
      required:
        - proceeding_code
      properties:
        id:
          type: string
          format: uuid
        proceeding_code:
          type: string
        level_of_service_code:
          type: string

    RecordHistory:
      required:
        - created_at
        - created_by
        - updated_at
        - updated_by
      properties:
        created_at:
          type: string
          format: date-time
        created_by:
          type: string
        updated_at:
          type: string
          format: date-time
        updated_by:
          type: string

    ApplicationCollection:
      type: array
      items:
        $ref: "#/components/schemas/Application"
