openapi: "3.0.0"
info:
  version: 1.0.0
  title: Applications API

paths:
  /api/v0/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      parameters:
        - in: query
          name: status
          description: The current overall status of the applications' decision.
          schema:
            $ref: "#/components/schemas/applicationStatus"
        - in: query
          name: reference
          description: The application reference
          schema:
            type: string
        - in: query
          name: page
          description: page number of data to be returned
          schema:
            type: integer
            default: 0
        - in: query
          name: pagesize
          description: number of applications in a page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSummaryResponse"
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '500': { description: Internal server error }
    post:
      tags:
        - application
      summary: Create an application
      operationId: createApplication
      requestBody:
        description: Create an application (all fields inside `applicationContent`)
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationCreateRequest"
      responses:
        '201': { description: Created }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '500': { description: Internal server error }

  /api/v0/applications/{id}:
    get:
      tags:
        - application
      summary: Get an application by id
      operationId: getApplicationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '500': { description: Internal server error }
    patch:
      tags:
        - application
      summary: Update an application
      operationId: updateApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Partial update of application (all fields inside `applicationContent`)
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationUpdateRequest"
      responses:
        '200': { description: Success }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '409': { description: Conflict }
        '500': { description: Internal server error }

components:
  schemas:
    applicationStatus:
      type: string
      enum:
        - IN_PROGRESS
        - SUBMITTED
      description: Application statuses

    Individual:
      type: object
      required:
        - firstName
        - lastName
        - dateOfBirth
      properties:
        firstName:
          type: string
        lastName:
          type: string
        dateOfBirth:
          type: string
          format: date
        details:
          type: object
          additionalProperties: true

    Application:
      type: object
      required:
        - id
        - applicationStatus
        - applicationContent
      properties:
        id:
          type: string
          format: uuid
        applicationStatus:
          $ref: "#/components/schemas/applicationStatus"
        schemaVersion:
          type: integer
        applicationContent:
          type: object
          additionalProperties: true
        linked_individuals:
          type: array
          items:
            $ref: "#/components/schemas/Individual"

    ApplicationCreateRequest:
      type: object
      required:
        - status
        - applicationContent
        - applicationReference
      properties:
        status:
          $ref: "#/components/schemas/applicationStatus"
        applicationContent:
          type: object
          additionalProperties: true
        applicationReference:
          type: string

    ApplicationUpdateRequest:
      type: object
      required:
        - applicationContent
      properties:
        status:
          $ref: "#/components/schemas/applicationStatus"
        applicationContent:
          type: object
          description: Application data to update
          additionalProperties: true

    ApplicationSummary:
      type: object
      description: (APPLICATION LIST PAGE / VIEW - OPEN APPLICATIONS ONLY BY DEFAULT)
      properties:
        application_id:
          type: string
          format: uuid
          description: The unique reference used to identify the application.
        applicationStatus:
          $ref: "#/components/schemas/applicationStatus"
        application_reference:
          type: string
        created_at:
          type: string
          format: date-time
        modified_at:
          type: string
          format: date-time

    ApplicationSummaryResponse:
      type: object
      properties:
        paging:
          type: object
          properties:
            page:
              type: integer
            page_size:
              type: integer
            items_returned:
              type: integer
            total_records:
              type: integer
        applications:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationSummary"
