openapi: "3.0.0"
info:
  version: 1.0.0
  title: Applications API

paths:
  /api/v0/applications:
    get:
      tags:
        - application
      summary: Get applications
      operationId: getApplications
      parameters:
        - in: query
          name: status
          description: The current overall status of the applications' decision.
          schema:
            $ref: "#/components/schemas/application_status"
        - in: query
          name: page
          description: page number of data to be returned
          schema:
            type: integer
            default: 0
        - in: query
          name: pagesize
          description: number of applications in a page
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApplicationSummaryResponse"
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '500': { description: Internal server error }
    post:
      tags:
        - application
      summary: Create an application
      operationId: createApplication
      requestBody:
        description: Create an application (all fields inside `applicationContent`)
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationCreateRequest"
      responses:
        '201': { description: Created }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '500': { description: Internal server error }

  /api/v0/applications/{id}:
    get:
      tags:
        - application
      summary: Get an application by id
      operationId: getApplicationById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Application"
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '500': { description: Internal server error }

    patch:
      tags:
        - application
      summary: Update an application
      operationId: updateApplication
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        description: Partial update of application (all fields inside `applicationContent`)
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ApplicationUpdateRequest"
      responses:
        '204': { description: No content }
        '400': { description: Bad request }
        '401': { description: Unauthorized }
        '403': { description: Forbidden }
        '404': { description: Not found }
        '500': { description: Internal server error }

components:
  schemas:
    Application:
      type: object
      required:
        - id
        - applicationStatus
        - applicationContent
      properties:
        id:
          type: string
          format: uuid
          description: UUIDv7 format
        applicationStatus:
          type: string
        schemaVersion:
          type: integer
        applicationContent:
          type: object
          additionalProperties: true
          description: Full JSON object representing all application fields

    ApplicationCreateRequest:
      type: object
      required:
        - statusId
        - applicationContent
      properties:
        statusId:
          type: string
          format: uuid
        schemaVersion:
          type: integer
        applicationContent:
          type: object
          additionalProperties: true
          description: All the application fields to store in JSONB

    ApplicationUpdateRequest:
      type: object
      properties:
        statusId:
          type: string
          format: uuid
        schemaVersion:
          type: integer
        applicationContent:
          type: object
          additionalProperties: true
          description: Partial update fields for JSONB

    ApplicationCollection:
      type: array
      items:
        $ref: "#/components/schemas/Application"

    ApplicationSummary:
      type: object
      description: (APPLICATION LIST PAGE / VIEW - OPEN APPLICATIONS ONLY BY DEFAULT)
      properties:
        application_id:
          type: string
          format: uuid
          description: The unique reference used to identify the application.
        application_status:
          $ref: "#/components/schemas/application_status"
        application_reference:
          type: string
        created_at:
          type: string
          format: date-time
          description: This is the date that the application was submitted. It is used for MI and prioritisation.
        modified_at:
          type: string
          format: date-time

    ApplicationSummaryResponse:
      type: object
      properties:
        paging:
          type: object
          properties:
            page:
              type: integer
            page_size:
              type: integer
            items_returned:
              type: integer
            total_records:
              type: integer
        applications:
          type: array
          items:
            $ref: "#/components/schemas/ApplicationSummary"

    application_status:
      type: string
      enum:
        - IN_PROGRESS
        - SUBMITTED
      default: IN_PROGRESS
      description: Application statuses
