services:
  postgres:
    image: postgres:17
    container_name: laa-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laa_data_access_api
      POSTGRES_USER: laa_user
      POSTGRES_PASSWORD: laa_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  localstack_data:
  pgdata:
