version: '3.8'
services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: laa_data_access_api
      POSTGRES_USER: laa_user
      POSTGRES_PASSWORD: laa_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:3.6.0
    ports:
      - "4566:4566" # LocalStack edge service (all services)
      - "4510-4559:4510-4559" # additional ports used by some services (optional)
    environment:
      - SERVICES=s3,dynamodb
      - PERSISTENCE=1 # persist data across container restarts
      - DEFAULT_REGION=eu-west-2
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_VOLUME_DIR=/var/lib/localstack
      - DYNAMODB_SHARE_DB=1 # share DynamoDB data across multiple LocalStack instances (optional)
    volumes:
      - localstack_state:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts:/etc/localstack/init/ready.d:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
  localstack_state:
